import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1rem",
      screens: { xs: "420px", "2xl": "1400px" },
    },
    extend: {
      colors: {
        coral: {
          DEFAULT: "#E8573A",
          light: "#F06B50",
          dark: "#D14A2E",
          50: "#FEF2EE",
          100: "#FDE1D9",
          200: "#FBC3B3",
          300: "#F89C84",
          400: "#F27455",
          500: "#E8573A",
          600: "#D14A2E",
          700: "#AE3A23",
          800: "#8B2E1C",
          900: "#682315",
        },
        primary: {
          DEFAULT: "#FFFFFF",
          light: "#FFFFFF",
          dark: "#0D0D0D",
          50: "#FFFFFF",
          100: "#F5F5F5",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A3A3A3",
          500: "#FFFFFF",
          600: "#E5E5E5",
          700: "#D4D4D4",
          800: "#A3A3A3",
          900: "#525252",
        },
        accent: {
          DEFAULT: "#E8573A",
          light: "#F06B50",
          dark: "#D14A2E",
          50: "#FEF2EE",
          100: "#FDE1D9",
          200: "#FBC3B3",
          300: "#F89C84",
          400: "#F27455",
          500: "#E8573A",
          600: "#D14A2E",
          700: "#AE3A23",
          800: "#8B2E1C",
          900: "#682315",
        },
        background: "#0D0D0D",
        foreground: "#FFFFFF",
        border: "#2A2A2A",
        input: "#2A2A2A",
        ring: "#E8573A",
      },
      fontFamily: {
        sans: ["Inter", "var(--font-inter)", "system-ui", "sans-serif"],
        heading: [
          "Poppins",
          "var(--font-poppins)",
          "Inter",
          "var(--font-inter)",
          "system-ui",
          "sans-serif",
        ],
        body: ["Inter", "var(--font-inter)", "system-ui", "sans-serif"],
        logo: [
          "Poppins",
          "var(--font-poppins)",
          "Inter",
          "var(--font-inter)",
          "system-ui",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "SF Mono", "Fira Code", "monospace"],
      },
      borderRadius: {
        sm: "6px",
        md: "10px",
        lg: "16px",
        xl: "20px",
      },
      boxShadow: {
        sm: "0 1px 3px rgba(0, 0, 0, 0.4)",
        md: "0 4px 12px rgba(0, 0, 0, 0.5)",
        lg: "0 8px 24px rgba(0, 0, 0, 0.6)",
        xl: "0 16px 48px rgba(0, 0, 0, 0.7)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.3" },
        },
        "check-draw": {
          "0%": { strokeDashoffset: "50" },
          "100%": { strokeDashoffset: "0" },
        },
        "slide-up": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        shimmer: "shimmer 1.5s infinite",
        "pulse-dot": "pulse-dot 1.5s ease-in-out infinite",
        "check-draw": "check-draw 0.4s ease-out forwards",
        "slide-up": "slide-up 0.3s ease-out",
      },
    },
  },
  plugins: [animate],
};
export default config;
